global:
  scrape_interval: 15s

scrape_configs:
- job_name: node-exporter
  static_configs:
    - targets: [node-exporter:9100]

- job_name: rails-app
  static_configs:
    - targets: [web:3000]
  metrics_path: /metrics
  scheme: https