global:
  scrape_interval: 15s

scrape_configs:
- job_name: node-exporter
  static_configs:
    - targets: [devkopa.dk]
  metrics_path: /node-metrics
  scheme: https

- job_name: rails-app
  static_configs:
    - targets: [devkopa.dk]
  metrics_path: /metrics
  scheme: https