default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] || "localhost" %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>