name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd="pg_isready -U devkopa"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AZURE_VM_GHCR_PAT }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'

      - name: Install Gems
        run: bundle install

      - name: Prepare DB
        run: bin/rails db:create db:schema:load --trace

      - name: Run RSpec with Coverage
        run: bundle exec rspec

      - name: Check coverage output
        run: |
          pwd
          ls -l coverage/
          cat coverage/coverage.json || echo "No JSON file generated!"

      - name: Convert coverage.json to Sonar format
        run: |
          ruby <<'EOF'
            require 'json'
            require 'pathname'

            root = Pathname.new(ENV['GITHUB_WORKSPACE'])
            input = JSON.parse(File.read('coverage/coverage.json'))
            output = { 'files' => {} }

            input['files'].each do |entry|
              # Normalize Windows paths
              abs = Pathname.new(entry['filename'].gsub('\\', '/'))
              rel = abs.relative_path_from(root).to_s

              output['files'][rel] = {
                'covered_percent' => entry['covered_percent'],
                'coverage' => {
                  'lines' => entry['coverage']['lines']
                }
              }
            end

            File.write('coverage/coverage_sonar.json', JSON.pretty_generate(output))
          EOF

      - name: Verify converted coverage
        run: cat coverage/coverage_sonar.json

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
